[project]
name = "dbrca-postgres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepagents>=0.6.3",
    "fastapi>=0.136.1",
    "langchain-openai>=1.2.1",
    "psycopg-binary>=3.3.4",
    "pymysql>=1.2.0",
    "sqlalchemy>=2.0.49",
    "uuid6>=2025.0.1",
    "uvicorn>=0.47.0",
]
